-- =====================================================
-- CLYVO CARE AI
-- MASTERING RELATIONAL AND NON-RELATIONAL DATABASE
-- SCRIPT COMPLETO OFICIAL
-- =====================================================

SET SERVEROUTPUT ON;

-- =====================================================
-- DROP TABLES
-- =====================================================

DROP TABLE TB_ALERTAS CASCADE CONSTRAINTS;
DROP TABLE TB_SCORES_RISCO_PETS CASCADE CONSTRAINTS;
DROP TABLE TB_HISTORICOS_CLINICOS CASCADE CONSTRAINTS;
DROP TABLE TB_MEDICAMENTOS CASCADE CONSTRAINTS;
DROP TABLE TB_VACINAS CASCADE CONSTRAINTS;
DROP TABLE TB_CONSULTAS CASCADE CONSTRAINTS;
DROP TABLE TB_PETS CASCADE CONSTRAINTS;
DROP TABLE TB_VETERINARIOS CASCADE CONSTRAINTS;
DROP TABLE TB_CLINICAS CASCADE CONSTRAINTS;
DROP TABLE TB_TUTORES CASCADE CONSTRAINTS;
DROP TABLE TB_LOG_ERRO CASCADE CONSTRAINTS;

-- =====================================================
-- TABELA: TUTOR
-- =====================================================

CREATE TABLE TB_TUTORES (

    ID_TUTOR NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    NOME_TUTOR VARCHAR2(100) NOT NULL,

    CPF_TUTOR VARCHAR2(14) NOT NULL UNIQUE,

    EMAIL_TUTOR VARCHAR2(120) NOT NULL UNIQUE,

    TELEFONE_TUTOR VARCHAR2(20),

    DATA_NASCIMENTO_TUTOR DATE,

    DT_CADASTRO_TUTOR DATE DEFAULT SYSDATE

);

-- =====================================================
-- TABELA: CLINICA
-- =====================================================

CREATE TABLE TB_CLINICAS (

    ID_CLINICA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    NOME_FANTASIA VARCHAR2(120) NOT NULL,

    CNPJ VARCHAR2(18) NOT NULL UNIQUE,

    TELEFONE_CLINICA VARCHAR2(20),

    EMAIL_CLINICA VARCHAR2(120) UNIQUE,

    ENDERECO_CLINICA VARCHAR2(200) NOT NULL

);

-- =====================================================
-- TABELA: VETERINARIO
-- =====================================================

CREATE TABLE TB_VETERINARIOS (

    ID_VETERINARIO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    NOME_VETERINARIO VARCHAR2(100) NOT NULL,

    CRMV VARCHAR2(20) NOT NULL UNIQUE,

    ESPECIALIDADE VARCHAR2(80),

    EMAIL_VETERINARIO VARCHAR2(120) UNIQUE,

    TELEFONE_VETERINARIO VARCHAR2(20),

    ID_CLINICA NUMBER NOT NULL,

    CONSTRAINT FK_VETERINARIO_CLINICA
        FOREIGN KEY (ID_CLINICA)
        REFERENCES TB_CLINICAS(ID_CLINICA)

);

-- =====================================================
-- TABELA: PET
-- =====================================================

CREATE TABLE TB_PETS (

    ID_PET NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    NOME_PET VARCHAR2(80) NOT NULL,

    ESPECIE VARCHAR2(40) NOT NULL,

    RACA VARCHAR2(60),

    SEXO CHAR(1) NOT NULL,

    COR VARCHAR2(40),

    PESO NUMBER(5,2),

    DATA_NASCIMENTO_PET DATE,

    STATUS_SAUDE VARCHAR2(40),

    ID_TUTOR NUMBER NOT NULL,

    CONSTRAINT CK_PET_SEXO
        CHECK (SEXO IN ('M', 'F')),

    CONSTRAINT CK_PET_PESO
        CHECK (PESO > 0),

    CONSTRAINT FK_PET_TUTOR
        FOREIGN KEY (ID_TUTOR)
        REFERENCES TB_TUTORES(ID_TUTOR)

);

-- =====================================================
-- TABELA: CONSULTA
-- =====================================================

CREATE TABLE TB_CONSULTAS (

    ID_CONSULTA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    DATA_CONSULTA DATE NOT NULL,

    MOTIVO_CONSULTA VARCHAR2(200) NOT NULL,

    DIAGNOSTICO_CONSULTA VARCHAR2(300),

    OBSERVACOES_CONSULTA VARCHAR2(500),

    RETORNO_RECOMENDADO DATE,

    ID_PET NUMBER NOT NULL,

    ID_VETERINARIO NUMBER NOT NULL,

    ID_CLINICA NUMBER NOT NULL,

    CONSTRAINT CK_RETORNO_CONSULTA
        CHECK (
            RETORNO_RECOMENDADO IS NULL
            OR RETORNO_RECOMENDADO >= DATA_CONSULTA
        ),

    CONSTRAINT FK_CONSULTA_PET
        FOREIGN KEY (ID_PET)
        REFERENCES TB_PETS(ID_PET),

    CONSTRAINT FK_CONSULTA_VETERINARIO
        FOREIGN KEY (ID_VETERINARIO)
        REFERENCES TB_VETERINARIOS(ID_VETERINARIO),

    CONSTRAINT FK_CONSULTA_CLINICA
        FOREIGN KEY (ID_CLINICA)
        REFERENCES TB_CLINICAS(ID_CLINICA)

);

-- =====================================================
-- TABELA: VACINA
-- =====================================================

CREATE TABLE TB_VACINAS (

    ID_VACINA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    NOME_VACINA VARCHAR2(100) NOT NULL,

    FABRICANTE VARCHAR2(100),

    DOSE VARCHAR2(30),

    DATA_APLICACAO DATE NOT NULL,

    PROXIMA_DOSE DATE,

    STATUS VARCHAR2(20) NOT NULL,

    ID_PET NUMBER NOT NULL,

    CONSTRAINT CK_VACINA_STATUS
        CHECK (STATUS IN ('PENDENTE', 'APLICADA', 'ATRASADA')),

    CONSTRAINT FK_VACINA_PET
        FOREIGN KEY (ID_PET)
        REFERENCES TB_PETS(ID_PET)

);

-- =====================================================
-- TABELA: MEDICAMENTO
-- =====================================================

CREATE TABLE TB_MEDICAMENTOS (

    ID_MEDICAMENTO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    NOME_MEDICAMENTO VARCHAR2(100) NOT NULL,

    DOSAGEM VARCHAR2(50),

    FREQUENCIA VARCHAR2(50),

    DATA_INICIO DATE NOT NULL,

    DATA_FIM DATE,

    OBSERVACAO VARCHAR2(300),

    ID_PET NUMBER NOT NULL,

    CONSTRAINT CK_MEDICAMENTO_DATA
        CHECK (
            DATA_FIM IS NULL
            OR DATA_FIM >= DATA_INICIO
        ),

    CONSTRAINT FK_MEDICAMENTO_PET
        FOREIGN KEY (ID_PET)
        REFERENCES TB_PETS(ID_PET)

);

-- =====================================================
-- TABELA: HISTORICO_CLINICO
-- =====================================================

CREATE TABLE TB_HISTORICOS_CLINICOS (

    ID_HISTORICO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    DESCRICAO_EVENTO VARCHAR2(500) NOT NULL,

    CATEGORIA VARCHAR2(50) NOT NULL,

    DATA_EVENTO DATE NOT NULL,

    NIVEL_RISCO VARCHAR2(20),

    ID_PET NUMBER NOT NULL,

    CONSTRAINT CK_HISTORICO_CATEGORIA
        CHECK (
            CATEGORIA IN (
                'PREVENTIVO',
                'TERAPEUTICO',
                'EMERGENCIA',
                'BEM_ESTAR'
            )
        ),

    CONSTRAINT CK_HISTORICO_RISCO
        CHECK (
            NIVEL_RISCO IN (
                'BAIXO',
                'MEDIO',
                'ALTO'
            )
        ),

    CONSTRAINT FK_HISTORICO_PET
        FOREIGN KEY (ID_PET)
        REFERENCES TB_PETS(ID_PET)

);

-- =====================================================
-- TABELA: ALERTAS
-- =====================================================

CREATE TABLE TB_ALERTAS (

    ID_ALERTA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    TIPO_ALERTA VARCHAR2(80) NOT NULL,

    MENSAGEM VARCHAR2(400) NOT NULL,

    PRIORIDADE VARCHAR2(20) NOT NULL,

    DATA_ALERTA DATE DEFAULT SYSDATE,

    STATUS VARCHAR2(20) NOT NULL,

    ID_PET NUMBER NOT NULL,

    CONSTRAINT CK_ALERTA_PRIORIDADE
        CHECK (PRIORIDADE IN ('BAIXA', 'MEDIA', 'ALTA')),

    CONSTRAINT CK_ALERTA_STATUS
        CHECK (STATUS IN ('ATIVO', 'RESOLVIDO', 'PENDENTE')),

    CONSTRAINT FK_ALERTA_PET
        FOREIGN KEY (ID_PET)
        REFERENCES TB_PETS(ID_PET)

);

-- =====================================================
-- TABELA: SCORE_RISCO_PET
-- =====================================================

CREATE TABLE TB_SCORES_RISCO_PETS (

    ID_SCORE NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    SCORE_RISCO NUMBER(5,2) NOT NULL,

    CLASSIFICACAO VARCHAR2(20) NOT NULL,

    DATA_CALCULO DATE DEFAULT SYSDATE,

    ID_PET NUMBER NOT NULL,

    CONSTRAINT CK_SCORE_RISCO
        CHECK (SCORE_RISCO BETWEEN 0 AND 100),

    CONSTRAINT CK_SCORE_CLASSIFICACAO
        CHECK (
            CLASSIFICACAO IN (
                'BAIXO',
                'MODERADO',
                'ALTO',
                'CRITICO'
            )
        ),

    CONSTRAINT FK_SCORE_PET
        FOREIGN KEY (ID_PET)
        REFERENCES TB_PETS(ID_PET)

);

-- =====================================================
-- TABELA: LOG_ERRO
-- =====================================================

CREATE TABLE TB_LOG_ERRO (

    ID_LOG NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    NOME_PROCEDURE VARCHAR2(100) NOT NULL,

    USUARIO_BANCO VARCHAR2(50) NOT NULL,

    DATA_ERRO DATE DEFAULT SYSDATE,

    CODIGO_ERRO NUMBER,

    MENSAGEM_ERRO VARCHAR2(4000)

);

-- =====================================================
-- INSERTS TUTOR
-- =====================================================

INSERT INTO TB_TUTORES VALUES (
    DEFAULT,
    'João Santana',
    '123.456.789-00',
    'joao@email.com',
    '(11)99999-1001',
    TO_DATE('07/09/2006','DD/MM/YYYY'),
    SYSDATE
);

INSERT INTO TB_TUTORES VALUES (
    DEFAULT,
    'Nycollas Ryan',
    '741.852.963-00',
    'nyc@email.com',
    '(11)99999-1003',
    TO_DATE('02/01/2007','DD/MM/YYYY'),
    SYSDATE
);

INSERT INTO TB_TUTORES VALUES (
    DEFAULT,
    'Felipe Ribeiro',
    '987.654.321-00',
    'felipe@email.com',
    '(11)99999-1002',
    TO_DATE('25/05/2007','DD/MM/YYYY'),
    SYSDATE
);

-- =====================================================
-- INSERTS CLINICA
-- =====================================================

INSERT INTO TB_CLINICAS  VALUES (
    DEFAULT,
    'Pet Care Saúde Animal',
    '12.345.678/0001-90',
    '(11)4002-8922',
    'contato@petcare.com',
    'Av. Paulista, 1000 - São Paulo'
);

INSERT INTO TB_CLINICAS VALUES (
    DEFAULT,
    'Vida Pet Hospital Veterinário',
    '98.765.432/0001-10',
    '(11)3555-7788',
    'contato@vidapet.com',
    'Rua Vergueiro, 550 - São Paulo'
);

-- =====================================================
-- INSERTS VETERINARIO
-- =====================================================

INSERT INTO TB_VETERINARIOS VALUES (
    DEFAULT,
    'Dra. Fernanda Camacho',
    'CRMV-SP-1001',
    'Clínica Geral',
    'fernanda@petcare.com',
    '(11)98888-1001',
    1
);

INSERT INTO TB_VETERINARIOS VALUES (
    DEFAULT,
    'Dr. Ricardo Linhares',
    'CRMV-SP-1002',
    'Dermatologia',
    'ricardo@vidapet.com',
    '(11)98888-1002',
    2
);

-- =====================================================
-- INSERTS PET
-- =====================================================

INSERT INTO TB_PETS VALUES (
    DEFAULT,
    'Bolt',
    'Cachorro',
    'Yorkshire Terrier',
    'M',
    'Preto',
    4.50,
    TO_DATE('10/08/2013','DD/MM/YYYY'),
    'Saudável',
    1
);

INSERT INTO TB_PETS VALUES (
    DEFAULT,
    'Sonic',
    'Cachorro',
    'Pastor Alemão',
    'M',
    'Preto e Marrom',
    30.00,
    TO_DATE('18/09/2022','DD/MM/YYYY'),
    'Monitoramento',
    2
);

INSERT INTO TB_PETS VALUES (
    DEFAULT,
    'Lola',
    'Cachorro',
    'Mini Maltes',
    'F',
    'Branca',
    3.20,
    TO_DATE('01/01/2013','DD/MM/YYYY'),
    'Tratamento',
    3
);

-- =====================================================
-- INSERTS CONSULTA
-- =====================================================

INSERT INTO TB_CONSULTAS VALUES (
    DEFAULT,
    SYSDATE - 20,
    'Check-up anual',
    'Animal saudável',
    'Sem alterações clínicas',
    SYSDATE + 180,
    1,
    1,
    1
);

INSERT INTO TB_CONSULTAS VALUES (
    DEFAULT,
    SYSDATE - 10,
    'Coceira intensa',
    'Dermatite alérgica',
    'Necessário acompanhamento',
    SYSDATE + 30,
    2,
    2,
    2
);

-- =====================================================
-- INSERTS VACINA
-- =====================================================

INSERT INTO TB_VACINAS VALUES (
    DEFAULT,
    'V10',
    'Zoetis',
    '1ª Dose',
    SYSDATE - 100,
    SYSDATE + 265,
    'APLICADA',
    1
);

INSERT INTO TB_VACINAS VALUES (
    DEFAULT,
    'Antirrábica',
    'Merial',
    'Dose Única',
    SYSDATE - 400,
    SYSDATE - 30,
    'ATRASADA',
    2
);

-- =====================================================
-- INSERTS MEDICAMENTO
-- =====================================================

INSERT INTO TB_MEDICAMENTOS VALUES (
    DEFAULT,
    'Apoquel',
    '5mg',
    '1 vez ao dia',
    SYSDATE - 10,
    SYSDATE + 20,
    'Tratamento dermatológico',
    2
);

INSERT INTO TB_MEDICAMENTOS VALUES (
    DEFAULT,
    'Prednisona',
    '10mg',
    '2 vezes ao dia',
    SYSDATE - 5,
    SYSDATE + 10,
    'Controle inflamatório',
    3
);

-- =====================================================
-- INSERTS HISTORICO
-- =====================================================

INSERT INTO TB_HISTORICOS_CLINICOS VALUES (
    DEFAULT,
    'Vacinação anual concluída',
    'PREVENTIVO',
    SYSDATE - 90,
    'BAIXO',
    1
);

INSERT INTO TB_HISTORICOS_CLINICOS VALUES (
    DEFAULT,
    'Início de tratamento dermatológico',
    'TERAPEUTICO',
    SYSDATE - 8,
    'MEDIO',
    2
);

-- =====================================================
-- INSERTS ALERTA
-- =====================================================

INSERT INTO TB_ALERTAS VALUES (
    DEFAULT,
    'Vacina atrasada',
    'A vacina antirrábica está vencida.',
    'ALTA',
    SYSDATE,
    'ATIVO',
    2
);

-- =====================================================
-- INSERTS SCORE
-- =====================================================

INSERT INTO TB_SCORE_RISCO_PETS VALUES (
    DEFAULT,
    15,
    'BAIXO',
    SYSDATE,
    1
);

INSERT INTO TB_SCORE_RISCO_PETS VALUES (
    DEFAULT,
    65,
    'ALTO',
    SYSDATE,
    2
);

INSERT INTO TB_SCORE_RISCO_PETS VALUES (
    DEFAULT,
    40,
    'MODERADO',
    SYSDATE,
    3
);

COMMIT;

-- =====================================================
-- PROCEDURE LOG
-- =====================================================

CREATE OR REPLACE PROCEDURE REGISTRAR_LOG_ERRO (
    P_NOME_PROCEDURE IN VARCHAR2,
    P_CODIGO_ERRO IN NUMBER,
    P_MENSAGEM_ERRO IN VARCHAR2
)
IS
BEGIN

    INSERT INTO TB_LOG_ERRO (
        NOME_PROCEDURE,
        USUARIO_BANCO,
        DATA_ERRO,
        CODIGO_ERRO,
        MENSAGEM_ERRO
    )
    VALUES (
        P_NOME_PROCEDURE,
        USER,
        SYSDATE,
        P_CODIGO_ERRO,
        P_MENSAGEM_ERRO
    );

END;
/

-- =====================================================
-- FUNCTION IDADE PET
-- =====================================================

CREATE OR REPLACE FUNCTION FN_IDADE_PET (
    P_ID_PET IN NUMBER
)
RETURN NUMBER
IS

    V_IDADE NUMBER;

BEGIN

    SELECT FLOOR(
        MONTHS_BETWEEN(
            SYSDATE,
            DATA_NASCIMENTO_PET
        ) / 12
    )
    INTO V_IDADE
    FROM TB_PETS
    WHERE ID_PET = P_ID_PET;

    RETURN V_IDADE;

EXCEPTION

    WHEN OTHERS THEN

        REGISTRAR_LOG_ERRO(
            'FN_IDADE_PET',
            SQLCODE,
            SQLERRM
        );

        RETURN NULL;

END;
/

-- =====================================================
-- FUNCTION CLASSIFICAR RISCO
-- =====================================================

CREATE OR REPLACE FUNCTION FN_CLASSIFICAR_RISCO (
    P_SCORE IN NUMBER
)
RETURN VARCHAR2
IS

    V_CLASSIFICACAO VARCHAR2(20);

BEGIN

    IF P_SCORE <= 25 THEN
        V_CLASSIFICACAO := 'BAIXO';

    ELSIF P_SCORE <= 50 THEN
        V_CLASSIFICACAO := 'MODERADO';

    ELSIF P_SCORE <= 75 THEN
        V_CLASSIFICACAO := 'ALTO';

    ELSE
        V_CLASSIFICACAO := 'CRITICO';
    END IF;

    RETURN V_CLASSIFICACAO;

END;
/

-- =====================================================
-- TRIGGER ALERTA VACINA
-- =====================================================

CREATE OR REPLACE TRIGGER TRG_ALERTA_VACINA_ATRASADA

AFTER INSERT ON TB_VACINAS

FOR EACH ROW

BEGIN

    IF :NEW.STATUS = 'ATRASADA' THEN

        INSERT INTO TB_ALERTAS (
            TIPO_ALERTA,
            MENSAGEM,
            PRIORIDADE,
            STATUS,
            ID_PET
        )
        VALUES (
            'Vacina atrasada',
            'Vacina vencida detectada automaticamente.',
            'ALTA',
            'ATIVO',
            :NEW.ID_PET
        );

    END IF;

END;
/

-- =====================================================
-- TRIGGER HISTORICO NOVO PET
-- =====================================================

CREATE OR REPLACE TRIGGER TRG_NOVO_PET_HISTORICO

AFTER INSERT ON TB_PETS

FOR EACH ROW

BEGIN

    INSERT INTO TB_HISTORICOS_CLINICOS (
        DESCRICAO_EVENTO,
        CATEGORIA,
        DATA_EVENTO,
        NIVEL_RISCO,
        ID_PET
    )
    VALUES (
        'Pet cadastrado no sistema.',
        'PREVENTIVO',
        SYSDATE,
        'BAIXO',
        :NEW.ID_PET
    );

END;
/

-- =====================================================
-- TRIGGER CLASSIFICAR RISCO
-- =====================================================

CREATE OR REPLACE TRIGGER TRG_CLASSIFICAR_RISCO

BEFORE INSERT ON TB_SCORE_RISCO_PETS

FOR EACH ROW

BEGIN

    :NEW.CLASSIFICACAO :=
        FN_CLASSIFICAR_RISCO(:NEW.SCORE_RISCO);

END;
/

-- =====================================================
-- CURSOR PETS EM RISCO
-- =====================================================

DECLARE

    CURSOR C_PETS_RISCO IS

        SELECT
            P.NOME_PET,
            S.SCORE_RISCO,
            S.CLASSIFICACAO
        FROM TB_PETS P
        INNER JOIN TB_SCORE_RISCO_PETS S
            ON P.ID_PET = S.ID_PET
        WHERE S.CLASSIFICACAO IN ('ALTO', 'CRITICO');

BEGIN

    FOR V_REGISTRO IN C_PETS_RISCO LOOP

        DBMS_OUTPUT.PUT_LINE(
            'PET: ' || V_REGISTRO.NOME_PET ||
            ' | SCORE: ' || V_REGISTRO.SCORE_RISCO ||
            ' | CLASSIFICAÇÃO: ' || V_REGISTRO.CLASSIFICACAO
        );

    END LOOP;

END;
/

-- =====================================================
-- VIEWS
-- =====================================================

CREATE OR REPLACE VIEW VW_PETS_RISCO AS

SELECT
    P.NOME_PET,
    S.SCORE_RISCO,
    S.CLASSIFICACAO
FROM TB_PETS P
INNER JOIN TB_SCORE_RISCO_PETS S
    ON P.ID_PET = S.ID_PET
WHERE S.CLASSIFICACAO IN ('ALTO', 'CRITICO');

CREATE OR REPLACE VIEW VW_VACINAS_ATRASADAS AS

SELECT
    P.NOME_PET,
    V.NOME_VACINA,
    V.PROXIMA_DOSE
FROM TB_PETS P
INNER JOIN TB_VACINAS V
    ON P.ID_PET = V.ID_PET
WHERE V.STATUS = 'ATRASADA';

CREATE OR REPLACE VIEW VW_CONSULTAS_RETORNO AS

SELECT
    P.NOME_PET,
    C.DATA_CONSULTA,
    C.RETORNO_RECOMENDADO
FROM TB_CONSULTAS C
INNER JOIN TB_PETS P
    ON P.ID_PET = C.ID_PET
WHERE C.RETORNO_RECOMENDADO >= SYSDATE;

-- =====================================================
-- TESTES
-- =====================================================

SELECT * FROM VW_PETS_RISCO;

SELECT * FROM VW_VACINAS_ATRASADAS;

SELECT * FROM VW_CONSULTAS_RETORNO;

SELECT
    NOME_PET,
    FN_IDADE_PET(ID_PET) AS IDADE
FROM TB_PETS;

SELECT
    SCORE_RISCO,
    FN_CLASSIFICAR_RISCO(SCORE_RISCO) AS CLASSIFICACAO
FROM TB_SCORE_RISCO_PETS;

COMMIT;